server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: reservation
          uri: http://localhost:8082
          predicates:
            - Path=/msgLists/**, 
        - id: send
          uri: http://localhost:8083
          predicates:
            - Path=/msgs/**, 
        - id: rater
          uri: http://localhost:8084
          predicates:
            - Path=/rates/**, 
        - id: monitoring
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/msgLists/**, 
        - id: send
          uri: http://send:8080
          predicates:
            - Path=/msgs/**, 
        - id: rater
          uri: http://rater:8080
          predicates:
            - Path=/rates/**, 
        - id: monitoring
          uri: http://monitoring:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
